"""Render and drift-check the human and machine reference outputs."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any

from fluent_case_layer.schema.export import SCHEMA_MODELS

from .catalog import build_catalog

GENERATED_MARKER = "<!-- Generated by python -m fluent_case_layer.reference; do not edit. -->"


def _json(value: Any) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _catalog_json(catalog: dict[str, Any]) -> str:
    """Keep catalog diffs entry-oriented without repeating indentation on every field."""

    def compact(value: Any) -> str:
        return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    lines = ["{"]
    keys = [key for key in catalog if key != "entries"]
    for key in keys:
        lines.append(f"  {json.dumps(key)}: {compact(catalog[key])},")
    lines.append('  "entries": [')
    for index, entry in enumerate(catalog["entries"]):
        comma = "," if index + 1 < len(catalog["entries"]) else ""
        lines.append(f"    {compact(entry)}{comma}")
    lines.extend(["  ]", "}", ""])
    return "\n".join(lines)


def _inline(value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    if isinstance(value, (dict, list)):
        rendered = json.dumps(value, sort_keys=True, ensure_ascii=False)
    else:
        rendered = str(value)
    return f"`{rendered.replace('`', '&#96;')}`"


def _text(value: Any) -> str:
    if value is None or value == "":
        return "—"
    if isinstance(value, (dict, list)):
        value = json.dumps(value, sort_keys=True, ensure_ascii=False)
    return str(value).replace("|", "\\|").replace("\n", "<br>")


def _values(values: list[Any]) -> str:
    return ", ".join(_inline(value) for value in values) if values else "—"


def _render_reference_index(catalog: dict[str, Any]) -> str:
    coverage = catalog["coverage"]
    lines = [
        GENERATED_MARKER,
        "",
        "# Dictionary reference",
        "",
        "This is the complete generated reference for the split Fluent case dictionary.",
        "It combines static Pydantic/JSON Schema facts with reviewed Fluent/PyFluent",
        "coupling metadata. The [machine catalog](catalog.json) contains the same entries",
        "for agents and tools.",
        "",
        f"Current catalog: **{coverage['total_entries']} entries** for Fluent",
        f"**{catalog['target'].get('fluent_version', 'unspecified')}**.",
        "",
        "| Dictionary | Purpose | Entries | Reference |",
        "| --- | --- | ---: | --- |",
    ]
    for document in catalog["documents"]:
        lines.append(
            f"| `{document['source_path']}` | {_text(document['purpose'])} | "
            f"{document['entry_count']} | [{document['title']}]({document['key']}.md) |"
        )
    lines.extend(
        [
            "",
            "## How to read an entry",
            "",
            "Each entry separates four facts:",
            "",
            "1. **Authored YAML** — type, requirement, default, choices, constraints, and variants.",
            "2. **Fluent concept** — the solver feature and activation/order constraints.",
            "3. **PyFluent interface** — settings object or command, option source, and path confidence.",
            "4. **Adapter support** — what this repository really executes today.",
            "",
            "Static YAML choices are not assumed to be the complete set accepted by every Fluent",
            "state. PyFluent allowed values and active/read-only state can be dynamic; see the",
            "[runtime discovery guide](../manual/runtime-discovery.md).",
            "",
            "See [coverage](coverage.md) for implementation status and the",
            "[documentation system](../manual/documentation-system.md) for provenance and update rules.",
            "",
        ]
    )
    return "\n".join(lines)


def _render_document(document: dict[str, Any], entries: list[dict[str, Any]]) -> str:
    status_counts = Counter(entry["coupling"]["adapter"]["status"] for entry in entries)
    lines = [
        GENERATED_MARKER,
        "",
        f"# {document['title']}",
        "",
        f"- Dictionary: `{document['source_path']}`",
        f"- Schema: [`{document['schema_file']}`](schemas/{document['schema_file']})",
        f"- Entries: **{len(entries)}**",
        "",
        document["purpose"],
        "",
        "Support summary: "
        + ", ".join(f"**{key}** {value}" for key, value in sorted(status_counts.items()))
        + ".",
        "",
        "The status describes the repository adapter, not whether Fluent itself supports the feature.",
        "",
        "## Entry index",
        "",
        "| Pointer | Requirement | Type | Static choices | Adapter |",
        "| --- | --- | --- | --- | --- |",
    ]
    for entry in entries:
        schema = entry["schema"]
        anchor = entry["reference"]["anchor"]
        lines.append(
            f"| [`{entry['pointer']}`](#{anchor}) | {schema['requirement']} | "
            f"{_values(schema['types'])} | {_values(schema['choices'] or schema['item_choices'])} | "
            f"**{entry['coupling']['adapter']['status']}** |"
        )
    lines.append("")
    for entry in entries:
        schema = entry["schema"]
        coupling = entry["coupling"]
        fluent = coupling.get("fluent", {})
        pyfluent = coupling.get("pyfluent", {})
        adapter = coupling.get("adapter", {})
        authoring = entry.get("authoring", {})
        lines.extend(
            [
                f'<a id="{entry["reference"]["anchor"]}"></a>',
                "",
                f"## `{entry['pointer']}`",
                "",
                entry["description"] or f"Authored key `{entry['key']}`.",
                "",
                f"Canonical ID: `{entry['id']}`",
                "",
                "### Authored YAML",
                "",
                "| Property | Value |",
                "| --- | --- |",
                f"| Type | {_values(schema['types'])} |",
                f"| Requirement | `{schema['requirement']}` |",
                f"| Default | {_inline(schema.get('default'))} |",
                f"| Choices | {_values(schema['choices'])} |",
                f"| List-item choices | {_values(schema['item_choices'])} |",
                f"| Constraints | {_text(schema['constraints'])} |",
                f"| Available in variants | {_values(schema['available_in'])} |",
                f"| Required in variants | {_values(schema['required_in'])} |",
                f"| Allowed units | {_values(authoring.get('allowed_units', []))} |",
                f"| Semantic constraints | {_text(authoring.get('semantic_constraints'))} |",
                f"| Example | {_inline(authoring.get('example'))} |",
                "",
                "### Fluent and PyFluent coupling",
                "",
                "| Layer | Value |",
                "| --- | --- |",
                f"| Fluent mode | {_inline(fluent.get('mode'))} |",
                f"| Fluent concept | {_text(fluent.get('concept'))} |",
                f"| Activation/order | {_text(fluent.get('activation'))} |",
                f"| PyFluent interface | {_inline(pyfluent.get('interface'))} |",
                f"| PyFluent path | {_inline(pyfluent.get('path'))} |",
                f"| Operation | {_inline(pyfluent.get('operation'))} |",
                f"| Option source | {_inline(pyfluent.get('option_source'))} |",
                f"| Path confidence | {_inline(pyfluent.get('confidence'))} |",
                "",
                "### Current adapter boundary",
                "",
                "| Property | Value |",
                "| --- | --- |",
                f"| Status | **{adapter.get('status')}** |",
                f"| Action | {_inline(adapter.get('action'))} |",
                f"| Implementation | {_inline(adapter.get('implementation'))} |",
                "",
                _text(adapter.get("note")),
                "",
            ]
        )
        if adapter.get("option_support"):
            lines.extend(
                [
                    "Option-specific support:",
                    "",
                    "| Option | Support |",
                    "| --- | --- |",
                ]
            )
            for option, status in adapter["option_support"].items():
                lines.append(f"| `{option}` | `{status}` |")
            lines.append("")
    return "\n".join(lines)


def _render_coverage(catalog: dict[str, Any]) -> str:
    coverage = catalog["coverage"]
    lines = [
        GENERATED_MARKER,
        "",
        "# Coupling coverage",
        "",
        "Coverage is deliberately conservative. A field being valid YAML does not mean the",
        "current PyFluent adapter can apply it. `planned` and `partial` entries remain visible",
        "so agents cannot mistake documentation coverage for execution coverage.",
        "",
        "## Overall",
        "",
        "| Status | Entries | Meaning |",
        "| --- | ---: | --- |",
    ]
    meanings = catalog["policy"]["status_meanings"]
    for status, count in coverage["by_status"].items():
        lines.append(f"| `{status}` | {count} | {_text(meanings.get(status))} |")
    lines.extend(
        [
            "",
            "## By dictionary",
            "",
            "| Dictionary | Total | Implemented | Partial | Planned | Declaration-only | N/A |",
            "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
        ]
    )
    by_document = coverage["by_document"]
    for document in catalog["documents"]:
        row = by_document[document["key"]]
        statuses = row["by_status"]
        lines.append(
            f"| [`{document['source_path']}`]({document['key']}.md) | {row['total']} | "
            f"{statuses.get('implemented', 0)} | {statuses.get('partial', 0)} | "
            f"{statuses.get('planned', 0)} | {statuses.get('declaration_only', 0)} | "
            f"{statuses.get('not_applicable', 0)} |"
        )
    lines.extend(
        [
            "",
            "## Promotion rule",
            "",
            "Promote a mapping to `implemented` only after its schema-to-operation transform,",
            "activation prerequisites, and observable postcondition are covered by adapter tests.",
            "A candidate PyFluent path or a successful manual console action is not sufficient.",
            "",
        ]
    )
    return "\n".join(lines)


def render_outputs() -> dict[Path, str]:
    """Return every generated repository-relative output as text."""

    catalog = build_catalog()
    catalog_text = _catalog_json(catalog)
    outputs = {
        Path("src/fluent_case_layer/reference/catalog.json"): catalog_text,
        Path("docs/reference/catalog.json"): catalog_text,
        Path("docs/reference/index.md"): _render_reference_index(catalog),
        Path("docs/reference/coverage.md"): _render_coverage(catalog),
    }
    for document in catalog["documents"]:
        selected = [entry for entry in catalog["entries"] if entry["document"] == document["key"]]
        outputs[Path("docs/reference") / f"{document['key']}.md"] = _render_document(
            document, selected
        )
    for filename, model in SCHEMA_MODELS.items():
        schema = model.model_json_schema(mode="validation")
        outputs[Path("docs/reference/schemas") / filename] = _json(schema)
    return {path: text if text.endswith("\n") else text + "\n" for path, text in outputs.items()}


def write_outputs(root: str | Path) -> list[Path]:
    """Write all generated outputs and return their absolute paths."""

    repository = Path(root).resolve()
    written = []
    for relative, content in render_outputs().items():
        path = repository / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def check_outputs(root: str | Path) -> list[str]:
    """Return drift diagnostics; an empty list means generated files are current."""

    repository = Path(root).resolve()
    expected = render_outputs()
    issues = []
    for relative, content in expected.items():
        path = repository / relative
        if not path.exists():
            issues.append(f"missing generated file: {relative}")
        elif path.read_text(encoding="utf-8") != content:
            issues.append(f"stale generated file: {relative}")
    reference_root = repository / "docs/reference"
    expected_paths = {(repository / path).resolve() for path in expected}
    if reference_root.exists():
        for path in reference_root.rglob("*"):
            if path.is_file() and path.resolve() not in expected_paths:
                first_line = path.read_text(encoding="utf-8", errors="ignore").splitlines()[:1]
                if first_line == [GENERATED_MARKER]:
                    issues.append(f"orphaned generated file: {path.relative_to(repository)}")
    return issues
